#!/usr/bin/env bash
# overview-gist.sh - Create a point-in-time project summary gist
set -euo pipefail

PROJECT_NAME=$(basename "$(pwd)")
DATE=$(date +%Y-%m-%d)
TIMESTAMP=$(date +%Y-%m-%dT%H:%M:%S)

# Check for required tools
command -v gh >/dev/null || { echo "Error: gh CLI required"; exit 1; }

# Generate summary
SUMMARY=$(cat <<EOF
# ${PROJECT_NAME} Overview - ${DATE}

Generated: ${TIMESTAMP}

## Conjectures (cprr)

\`\`\`
$(./cprr list 2>/dev/null || echo "cprr not available")
\`\`\`

**Summary:** $(./cprr list 2>/dev/null | grep -c confirmed || echo 0) confirmed, $(./cprr list 2>/dev/null | grep -c testing || echo 0) testing

## Issues (beads)

\`\`\`
$(bd list --status open 2>/dev/null || echo "bd not available")
\`\`\`

## Experiments

$(ls -d experiments/[0-9]*/ 2>/dev/null | while read dir; do
    name=$(basename "$dir")
    status="unknown"
    [ -f "$dir/PROOF.md" ] && status="CONFIRMED"
    [ -f "$dir/REFUTATION.md" ] && grep -q "REFUTED" "$dir/REFUTATION.md" 2>/dev/null && status="REFUTED"
    echo "- ${name}: ${status}"
done || echo "No experiments found")

## In-Flight Branches

\`\`\`
$(git branch -r 2>/dev/null | grep -v HEAD | grep feat/ | sed 's/origin\///' || echo "None")
\`\`\`

## Local Worktrees

\`\`\`
$(git worktree list 2>/dev/null | tail -n +2 || echo "None")
\`\`\`

---
*Generated by \`gmake overview-gist\`*
EOF
)

# Create gist (private by default per user preferences)
echo "$SUMMARY" | gh gist create --filename "${PROJECT_NAME}-overview-${DATE}.md" --desc "${PROJECT_NAME} project overview ${DATE}"
